import './globals.css';

import { ReactNode } from 'react';
import { MuiSetup } from '@/app/utils/MuiSetup';

export const metadata = {
  title:       'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <MuiSetup>
          <div className='container'>{children}</div>
        </MuiSetup>
      </body>
    </html>
  );
}
