import './globals.css';
import './preflight.css';

import { ReactNode } from 'react';
import { NextAppDirEmotionCacheProvider } from 'tss-react/next';
import AppThemeProvider from '@/utils/AppThemeProvider';

export const metadata = {
  title:       'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='flex justify-center w-full h-screen'>
        <NextAppDirEmotionCacheProvider options={{ key: 'css' }}>
          <AppThemeProvider>{children}</AppThemeProvider>
        </NextAppDirEmotionCacheProvider>
      </body>
    </html>
  );
}
