import { ReactNode } from 'react';

export const metadata = {
  title:       'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }: { children: ReactNode }) {
  return (
    <div className='flex justify-center'>{children}</div>
  );
}
